# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grokbot/_proto/aiserver/v1/AiService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grokbot/_proto/aiserver/v1/AiService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grokbot._proto.aiserver.v1 import types_pb2 as grokbot_dot___proto_dot_aiserver_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*grokbot/_proto/aiserver/v1/AiService.proto\x12\x0b\x61iserver.v1\x1a&grokbot/_proto/aiserver/v1/types.proto2\xf5\x04\n\tAiService\x12\\\n\x0f\x41vailableModels\x12#.aiserver.v1.AvailableModelsRequest\x1a$.aiserver.v1.AvailableModelsResponse\x12}\n\x1aReportClientNumericMetrics\x12..aiserver.v1.ReportClientNumericMetricsRequest\x1a/.aiserver.v1.ReportClientNumericMetricsResponse\x12w\n\x18ReportSandProcessMetrics\x12,.aiserver.v1.ReportSandProcessMetricsRequest\x1a-.aiserver.v1.ReportSandProcessMetricsResponse\x12_\n\x10RunGenerateImage\x12$.aiserver.v1.RunGenerateImageRequest\x1a%.aiserver.v1.RunGenerateImageResponse\x12S\n\x0cTextToSpeech\x12 .aiserver.v1.TextToSpeechRequest\x1a!.aiserver.v1.TextToSpeechResponse\x12\\\n\x0fTranscribeAudio\x12#.aiserver.v1.TranscribeAudioRequest\x1a$.aiserver.v1.TranscribeAudioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grokbot._proto.aiserver.v1.AiService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AISERVICE']._serialized_start=100
  _globals['_AISERVICE']._serialized_end=729
# @@protoc_insertion_point(module_scope)
