# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grokbot/_proto/aiserver/v1/AnalyticsService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grokbot/_proto/aiserver/v1/AnalyticsService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grokbot._proto.aiserver.v1 import types_pb2 as grokbot_dot___proto_dot_aiserver_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1grokbot/_proto/aiserver/v1/AnalyticsService.proto\x12\x0b\x61iserver.v1\x1a&grokbot/_proto/aiserver/v1/types.proto2\x8f\x06\n\x10\x41nalyticsService\x12P\n\x0bTrackEvents\x12\x1f.aiserver.v1.TrackEventsRequest\x1a .aiserver.v1.TrackEventsResponse\x12>\n\x05\x42\x61tch\x12\x19.aiserver.v1.BatchRequest\x1a\x1a.aiserver.v1.BatchResponse\x12_\n\x10\x42ootstrapStatsig\x12$.aiserver.v1.BootstrapStatsigRequest\x1a%.aiserver.v1.BootstrapStatsigResponse\x12\x86\x01\n\x1dGetFirstWindowStatsigDecision\x12\x31.aiserver.v1.GetFirstWindowStatsigDecisionRequest\x1a\x32.aiserver.v1.GetFirstWindowStatsigDecisionResponse\x12M\n\nSubmitLogs\x12\x1e.aiserver.v1.SubmitLogsRequest\x1a\x1f.aiserver.v1.SubmitLogsResponse\x12\x65\n\x12IngestConversation\x12&.aiserver.v1.IngestConversationRequest\x1a\'.aiserver.v1.IngestConversationResponse\x12_\n\x10UploadIssueTrace\x12$.aiserver.v1.UploadIssueTraceRequest\x1a%.aiserver.v1.UploadIssueTraceResponse\x12h\n\x13\x44ownloadIssueTraces\x12\'.aiserver.v1.DownloadIssueTracesRequest\x1a(.aiserver.v1.DownloadIssueTracesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grokbot._proto.aiserver.v1.AnalyticsService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYTICSSERVICE']._serialized_start=107
  _globals['_ANALYTICSSERVICE']._serialized_end=890
# @@protoc_insertion_point(module_scope)
