# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grokbot/_proto/aiserver/v1/BackgroundComposerService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grokbot/_proto/aiserver/v1/BackgroundComposerService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grokbot._proto.aiserver.v1 import types_pb2 as grokbot_dot___proto_dot_aiserver_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:grokbot/_proto/aiserver/v1/BackgroundComposerService.proto\x12\x0b\x61iserver.v1\x1a&grokbot/_proto/aiserver/v1/types.proto2\xb0\x01\n\x19\x42\x61\x63kgroundComposerService\x12\x92\x01\n!GetBackgroundComposerUserSettings\x12\x35.aiserver.v1.GetBackgroundComposerUserSettingsRequest\x1a\x36.aiserver.v1.GetBackgroundComposerUserSettingsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grokbot._proto.aiserver.v1.BackgroundComposerService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BACKGROUNDCOMPOSERSERVICE']._serialized_start=116
  _globals['_BACKGROUNDCOMPOSERSERVICE']._serialized_end=292
# @@protoc_insertion_point(module_scope)
