"""Agent resource API: CRUD, capabilities, sessions, todos.

Wraps GrokBotService: ListGrokBotAgents, CreateGrokBotAgent,
UpdateGrokBotAgent, DeleteGrokBotAgent, GetGrokBotRuntimeCapabilities,
ListGrokBotAgentSessions, ListGrokBotAgentTodos.
"""
from __future__ import annotations


class AgentAPI:
    """Accessed via `client.agents`. See docs/API.md#agentapi."""

    async def list(self, *, include_team: bool = False, role: str | None = None): ...
    async def get(self, agent_id: str): ...
    async def create(self, *, name: str, description: str = "", harness: str = "box", **kw): ...
    async def update(self, agent_id: str, **fields): ...
    async def delete(self, agent_id: str) -> None: ...
    async def capabilities(self): ...
    async def sessions(self, agent_id: str): ...
    async def todos(self, agent_id: str): ...
